/**
 * new-problem — append a correctly formatted problem stub to a solution file.
 *
 *   cd site && npm run new-problem -- https://leetcode.com/problems/two-sum/
 *
 * The site is generated by parsing header comments out of the solution files,
 * so a typo'd header means a silently missing (or CI-failing) problem. This
 * script exists so the header is never hand-typed.
 *
 * SAFETY CONTRACT: this script only ever INSERTS lines. It never edits,
 * reorders, reformats or deletes a single existing line. It shows you exactly
 * what it will insert and asks before touching anything.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createInterface } from 'node:readline/promises';
import { resolve, join } from 'node:path';

const REPO_ROOT = resolve(import.meta.dirname, '..', '..');

type Source = 'leetcode' | 'hackerrank';
type Difficulty = 'Easy' | 'Medium' | 'Hard';
type Lang = 'python' | 'java' | 'javascript' | 'typescript' | 'c';

interface Target {
  lang: Lang;
  label: string;
  /** Repo-relative path. */
  file: string;
  source: Source;
}

/**
 * Where each language lives. Note "typesript.ts" — the filename is misspelled
 * in the repo and that is deliberate here; do not "fix" it.
 */
const TARGETS: Target[] = [
  { lang: 'python', label: 'Python', file: 'Leet Code/python.py', source: 'leetcode' },
  { lang: 'java', label: 'Java', file: 'Leet Code/java.java', source: 'leetcode' },
  { lang: 'javascript', label: 'JavaScript', file: 'Leet Code/javascript.js', source: 'leetcode' },
  { lang: 'typescript', label: 'TypeScript', file: 'Leet Code/typesript.ts', source: 'leetcode' },
  { lang: 'c', label: 'C', file: 'Leet Code/c.c', source: 'leetcode' },
  { lang: 'python', label: 'Python (HackerRank)', file: 'Hacker Rank/python.py', source: 'hackerrank' },
];

/**
 * `# 217. Title (url) - Easy [tag]`, or the `//` equivalent.
 *
 * Deliberately more permissive than what this script writes: the title is lazy
 * so titles containing parentheses still match, and the difficulty is optional
 * because a few existing JS/TS headers omit it. Reading is lenient so that
 * existing blocks are always found; writing is always fully formed.
 */
const LC_HEADER =
  /^(\s*)(?:#+|\/\/)\s*(\d+)\.\s*(.+?)\s*\((https?:\/\/[^)\s]+)\)\s*(?:-\s*(Easy|Medium|Hard)\b)?\s*(.*)$/i;

/** `#<< Title (url) - Medium [tag]` */
const HR_HEADER =
  /^(\s*)#<<\s*(.+?)\s*\((https?:\/\/[^)\s]+)\)\s*(?:-\s*(Easy|Medium|Hard)\b)?\s*(.*)$/i;

/** `[approach-tag]` suffix, read out of whatever trails the difficulty. */
const TAG_RE = /\[([^\]]+)\]/;

/**
 * Trailing driver/scratch sections. Solutions placed here are not picked up by
 * the parser, so they are never offered as an insertion target.
 */
const TAIL_BANNER = /^TEST(?:ING|\s*CASES?)?$/i;

/**
 * Section banner, in any of the four styles used across the repo:
 *   ####### ARRAYS AND HASHING #######
 *   //#######  ARRAYS AND HASHING  #######//
 *   // ##### LINKED LIST ##### //
 *   #---------------------- TREE ----------------------#
 */
const BANNER = /^[#-]{3,}\s*([^#\s-][^#]*?)\s*[#-]{3,}$/;

// ---------------------------------------------------------------- utilities

const isTTY = Boolean(process.stdin.isTTY);
const color = (code: string, s: string) => (process.stdout.isTTY ? `\x1b[${code}m${s}\x1b[0m` : s);
const green = (s: string) => color('32', s);
const yellow = (s: string) => color('33', s);
const dim = (s: string) => color('2', s);

function fail(message: string): never {
  console.error(`\n${color('31', 'error')} ${message}\n`);
  process.exit(1);
}

function indentWidth(line: string): number {
  return line.length - line.trimStart().length;
}

/** "contains-duplicate" -> "Contains Duplicate" */
function titleFromSlug(slug: string): string {
  const ROMAN = new Set(['ii', 'iii', 'iv', 'vi', 'vii', 'viii', 'ix']);
  return slug
    .split('-')
    .filter(Boolean)
    .map((w) => (ROMAN.has(w) ? w.toUpperCase() : w[0].toUpperCase() + w.slice(1)))
    .join(' ');
}

/** "Contains Duplicate" -> "containsDuplicate" */
function camelFromTitle(title: string): string {
  const words = title.replace(/[^A-Za-z0-9 ]/g, ' ').split(/\s+/).filter(Boolean);
  if (words.length === 0) return 'solve';
  const camel = words
    .map((w, i) => (i === 0 ? w[0].toLowerCase() + w.slice(1) : w[0].toUpperCase() + w.slice(1)))
    .join('');
  return /^[A-Za-z]/.test(camel) ? camel : `solve${camel}`;
}

function detectBanner(line: string): string | null {
  // Normalise the two comment styles away, then match one generic banner shape.
  const stripped = line.trim().replace(/^\/\//, '').replace(/\/\/$/, '').trim();
  const m = stripped.match(BANNER);
  return m ? m[1].trim() : null;
}

function matchHeader(line: string, source: Source) {
  return source === 'hackerrank' ? line.match(HR_HEADER) : line.match(LC_HEADER);
}

// -------------------------------------------------------------------- input

/** The flags that take a string value. Kept as a const so parseArgs can both
 *  validate against it and index into Flags without an unsafe cast. */
const STRING_FLAGS = ['url', 'number', 'title', 'difficulty', 'lang', 'tag', 'section'] as const;

type StringFlag = (typeof STRING_FLAGS)[number];

type Flags = { [K in StringFlag]?: string } & {
  dryRun: boolean;
  help: boolean;
};

function parseArgs(argv: string[]): Flags {
  const flags: Flags = { dryRun: false, help: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--dry-run') flags.dryRun = true;
    else if (arg === '--help' || arg === '-h') flags.help = true;
    else if (arg.startsWith('--')) {
      // Support both `--key value` and `--key=value`.
      const eq = arg.indexOf('=');
      const key = (eq === -1 ? arg.slice(2) : arg.slice(2, eq)).replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      const value = eq === -1 ? argv[++i] : arg.slice(eq + 1);
      if (value === undefined) fail(`missing value for --${key}`);
      if (!STRING_FLAGS.includes(key as StringFlag)) {
        fail(`unknown flag --${key}. Run with --help.`);
      }
      flags[key as StringFlag] = value;
    } else if (!flags.url) {
      flags.url = arg; // bare positional is the URL
    } else {
      fail(`unexpected argument "${arg}". Run with --help.`);
    }
  }
  return flags;
}

const HELP = `
new-problem — append a correctly formatted problem stub to a solution file.

Usage
  npm run new-problem -- <leetcode-or-hackerrank-url> [options]

Options
  --url <url>            Problem URL (or pass it as the first argument)
  --number <n>           LeetCode problem number
  --title <text>         Problem title (default: derived from the URL slug)
  --difficulty <level>   Easy | Medium | Hard
  --lang <lang>          python | java | javascript | typescript | c
  --tag <slug>           Approach tag, e.g. sorted-key. Blocks that share a tag
                         are merged into one approach with per-language tabs.
  --section <name>       Category section to insert under, e.g. "ARRAYS AND HASHING"
  --dry-run              Print the preview and exit without writing
  -h, --help             Show this help

Anything not supplied is asked for interactively.
This script only inserts lines; it never modifies existing ones.
`;

let rl: ReturnType<typeof createInterface> | null = null;

/** Closing goes through a function so the readline handle is released even when
 *  no prompt was ever opened (all flags supplied, or --dry-run from a script). */
function closePrompt(): void {
  rl?.close();
  rl = null;
}

async function ask(question: string, fallback?: string): Promise<string> {
  if (!isTTY) {
    // Non-interactive (CI, a pipe, --dry-run from a script): take the derived
    // default if there is one, otherwise there is nothing sensible to do.
    if (fallback !== undefined) return fallback;
    fail(
      `need a value for "${question.trim()}" but stdin is not a terminal.\n` +
        `        Pass it as a flag, or run interactively. See --help.`,
    );
  }
  rl ??= createInterface({ input: process.stdin, output: process.stdout });
  const suffix = fallback ? dim(` [${fallback}]`) : '';
  const answer = (await rl.question(`${question}${suffix}: `)).trim();
  return answer || fallback || '';
}

async function askChoice<T>(question: string, options: { label: string; value: T }[]): Promise<T> {
  console.log(`\n${question}`);
  options.forEach((o, i) => console.log(`  ${String(i + 1).padStart(2)}) ${o.label}`));
  while (true) {
    const raw = await ask('Choice');
    const n = Number(raw);
    if (Number.isInteger(n) && n >= 1 && n <= options.length) return options[n - 1].value;
    console.log(yellow(`  Enter a number between 1 and ${options.length}.`));
  }
}

// ------------------------------------------------------------------ scanning

interface Existing {
  file: string;
  line: number;
  number?: number;
  title: string;
  url: string;
  /** Absent on the handful of existing headers that omit it. */
  difficulty?: Difficulty;
  tag?: string;
}

function normaliseDifficulty(raw: string | undefined): Difficulty | undefined {
  if (!raw) return undefined;
  return (raw[0].toUpperCase() + raw.slice(1).toLowerCase()) as Difficulty;
}

/** Every problem header currently in the repo, so we can reuse known metadata. */
function scanAll(): Existing[] {
  const found: Existing[] = [];
  for (const t of TARGETS) {
    const abs = join(REPO_ROOT, t.file);
    if (!existsSync(abs)) continue;
    const lines = readFileSync(abs, 'utf8').split(/\r?\n/);
    lines.forEach((line, i) => {
      const m = matchHeader(line, t.source);
      if (!m) return;
      found.push(
        t.source === 'hackerrank'
          ? {
              file: t.file,
              line: i + 1,
              title: m[2],
              url: m[3],
              difficulty: normaliseDifficulty(m[4]),
              tag: m[5]?.match(TAG_RE)?.[1],
            }
          : {
              file: t.file,
              line: i + 1,
              number: Number(m[2]),
              title: m[3],
              url: m[4],
              difficulty: normaliseDifficulty(m[5]),
              tag: m[6]?.match(TAG_RE)?.[1],
            },
      );
    });
  }
  return found;
}

interface Banner {
  index: number;
  name: string;
}

function findBanners(lines: string[]): Banner[] {
  const banners: Banner[] = [];
  lines.forEach((line, i) => {
    const name = detectBanner(line);
    if (name) banners.push({ index: i, name });
  });
  return banners;
}

/**
 * Where to insert inside a section: directly after the last problem block it
 * already contains.
 *
 * The end of that block is found by walking forward from its header and
 * stopping at the first line that dedents out of it. That is what keeps a Java
 * insertion inside `class Solution { ... }` instead of landing after the class'
 * closing brace when the chosen section is the last one in the file.
 */
function insertionPoint(lines: string[], bannerIdx: number, boundary: number, source: Source) {
  let lastHeader = -1;
  for (let i = bannerIdx + 1; i < boundary; i++) {
    if (matchHeader(lines[i], source)) lastHeader = i;
  }

  if (lastHeader === -1) {
    // Empty section: sit right under the banner and borrow its indentation.
    return { at: bannerIdx + 1, indent: indentWidth(lines[bannerIdx]) };
  }

  const indent = indentWidth(lines[lastHeader]);
  let at = lastHeader + 1;
  for (let i = lastHeader + 1; i < boundary; i++) {
    const line = lines[i];
    if (line.trim() === '') continue; // blank lines can be interior to a block
    if (indentWidth(line) < indent) break; // dedented out — end of the block
    at = i + 1;
  }
  return { at, indent };
}

// -------------------------------------------------------------------- stubs

interface StubInput {
  source: Source;
  lang: Lang;
  number?: number;
  title: string;
  url: string;
  difficulty: Difficulty;
  tag?: string;
  indent: number;
}

function renderStub(o: StubInput): string[] {
  const tagSuffix = o.tag ? ` [${o.tag}]` : '';
  // Stamp today so an attempt date is never a thing you remember to type. Built from
  // local parts rather than toISOString(), which would roll over to tomorrow for an
  // evening solve west of UTC. Append the solve time by hand: `- 2026-08-17 - 14m`.
  const now = new Date();
  const dated = ` - ${now.getFullYear()}-${`${now.getMonth() + 1}`.padStart(2, '0')}-${`${now.getDate()}`.padStart(2, '0')}`;
  const fn = camelFromTitle(o.title);

  if (o.source === 'hackerrank') {
    // HackerRank blocks are explicitly delimited and always top level.
    return [
      `#<< ${o.title} (${o.url}) - ${o.difficulty}${dated}${tagSuffix}`,
      `def ${fn}():`,
      `    '''`,
      `    Time Complexity: TODO`,
      `    Space Complexity: TODO`,
      `    '''`,
      `    pass`,
      `#>>`,
      ``,
    ];
  }

  if (o.lang === 'python') {
    // Python solutions are module level, so indentation is always zero.
    return [
      `# ${o.number}. ${o.title} (${o.url}) - ${o.difficulty}${dated}${tagSuffix}`,
      `class Solution:`,
      `    '''`,
      `    Time Complexity: TODO`,
      `    Space Complexity: TODO`,
      `    '''`,
      `    def ${fn}(self):`,
      `        pass`,
      ``,
    ];
  }

  const pad = ' '.repeat(o.indent);
  const body: Record<Exclude<Lang, 'python'>, string[]> = {
    java: [`public void ${fn}() {`, `    // TODO`, `}`],
    javascript: [`var ${fn} = function () {`, `    // TODO`, `};`],
    typescript: [`function ${fn}(): void {`, `    // TODO`, `}`],
    c: [`void ${fn}() {`, `    // TODO`, `}`],
  };

  return [
    `${pad}// ${o.number}. ${o.title} (${o.url}) - ${o.difficulty}${dated}${tagSuffix}`,
    `${pad}/**`,
    `${pad} * Time Complexity: TODO`,
    `${pad} * Space Complexity: TODO`,
    `${pad} */`,
    ...body[o.lang as Exclude<Lang, 'python'>].map((l) => pad + l),
    ``,
  ];
}

function printPreview(file: string, lines: string[], at: number, stub: string[]) {
  const CONTEXT = 3;
  console.log(`\n${dim('--- ' + file)}`);
  console.log(`${dim('+++ ' + file)}`);
  console.log(dim(`@@ inserting ${stub.length} line(s) at line ${at + 1} @@`));
  for (let i = Math.max(0, at - CONTEXT); i < at; i++) console.log(dim('  ' + lines[i]));
  for (const l of stub) console.log(green('+ ' + l));
  for (let i = at; i < Math.min(lines.length, at + CONTEXT); i++) console.log(dim('  ' + lines[i]));
  console.log('');
}

// --------------------------------------------------------------------- main

async function main() {
  const flags = parseArgs(process.argv.slice(2));
  if (flags.help) {
    console.log(HELP);
    return;
  }

  // 1. URL -> source + slug, normalised to the form used throughout the repo.
  const rawUrl = flags.url ?? (await ask('Problem URL'));
  let source: Source;
  let slug: string;
  let url: string;

  const lc = rawUrl.match(/leetcode\.com\/problems\/([a-z0-9-]+)/i);
  const hr = rawUrl.match(/hackerrank\.com\/(?:[\w-]+\/)*challenges\/([a-z0-9-]+)/i);
  if (lc) {
    source = 'leetcode';
    slug = lc[1].toLowerCase();
    url = `https://leetcode.com/problems/${slug}/description/`;
  } else if (hr) {
    source = 'hackerrank';
    slug = hr[1].toLowerCase();
    url = `https://www.hackerrank.com/challenges/${slug}/problem`;
  } else {
    return fail(
      `could not read a problem slug from "${rawUrl}".\n` +
        `        Expected https://leetcode.com/problems/<slug>/ or\n` +
        `                 https://www.hackerrank.com/challenges/<slug>/problem`,
    );
  }

  // 2. Reuse metadata already written elsewhere in the repo for this problem.
  const all = scanAll();
  const known = all.filter((e) => e.url.includes(`/${slug}/`));

  // 3. Which file are we appending to?
  const candidates = TARGETS.filter((t) => t.source === source);
  let target: Target;
  if (flags.lang) {
    const wanted = flags.lang.toLowerCase();
    const found = candidates.find((t) => t.lang === wanted || t.label.toLowerCase() === wanted);
    if (!found) fail(`no ${source} file for language "${flags.lang}". Options: ${candidates.map((t) => t.lang).join(', ')}`);
    target = found;
  } else if (candidates.length === 1) {
    target = candidates[0];
  } else {
    target = await askChoice(
      'Which file should this go in?',
      candidates.map((t) => ({ label: `${t.label.padEnd(22)} ${dim(t.file)}`, value: t })),
    );
  }

  const abs = join(REPO_ROOT, target.file);
  if (!existsSync(abs)) fail(`${target.file} does not exist.`);

  // 4. Number / title / difficulty. The LeetCode URL slug carries the title but
  //    never the number, so the number is asked for unless we already know it.
  let number: number | undefined;
  if (source === 'leetcode') {
    const guess = flags.number ?? known.find((k) => k.number !== undefined)?.number?.toString() ?? '';
    const answer = guess || (await ask('Problem number'));
    number = Number(answer);
    if (!Number.isInteger(number) || number <= 0) fail(`"${answer}" is not a valid problem number.`);
  }

  const titleGuess = flags.title ?? known[0]?.title ?? titleFromSlug(slug);
  const title = flags.title ?? (await ask('Title', titleGuess));

  const diffGuess = flags.difficulty ?? known.find((k) => k.difficulty)?.difficulty;
  let difficulty: Difficulty;
  if (diffGuess) {
    const normalised = diffGuess[0].toUpperCase() + diffGuess.slice(1).toLowerCase();
    if (!['Easy', 'Medium', 'Hard'].includes(normalised)) fail(`difficulty must be Easy, Medium or Hard (got "${diffGuess}").`);
    difficulty = normalised as Difficulty;
  } else {
    difficulty = await askChoice('Difficulty?', [
      { label: 'Easy', value: 'Easy' as Difficulty },
      { label: 'Medium', value: 'Medium' as Difficulty },
      { label: 'Hard', value: 'Hard' as Difficulty },
    ]);
  }

  // 5. Solved before? Then tags are what stop the site showing this as an
  //    unrelated duplicate instead of another approach / another language tab.
  const sameFile = known.filter((k) => k.file === target.file);
  const otherFiles = known.filter((k) => k.file !== target.file);
  const knownTags = [...new Set(otherFiles.concat(sameFile).map((k) => k.tag).filter(Boolean))];
  let tag = flags.tag;

  if (sameFile.length > 0) {
    console.log(
      yellow(`\nNote: "${title}" already appears in ${target.file} at line(s) ${sameFile.map((s) => s.line).join(', ')}.`),
    );
    console.log(
      `This new block will be treated as an ${color('1', 'additional approach')}.\n` +
        `Untagged blocks each render as their own approach. To group blocks — either two\n` +
        `approaches you consider the same, or the same approach across languages — give\n` +
        `them a matching ${color('1', '[tag]')}, e.g. ${dim(`- ${difficulty} [sorted-key]`)}`,
    );
  } else if (otherFiles.length > 0) {
    const where = [...new Set(otherFiles.map((k) => k.file))].join(', ');
    console.log(yellow(`\nNote: "${title}" is already solved in ${where}.`));
    console.log(
      `If this is the ${color('1', 'same approach')} in another language, give both a matching ${color('1', '[tag]')}\n` +
        `so the site merges them into one approach with per-language tabs.`,
    );
  }

  if (sameFile.length > 0 || otherFiles.length > 0) {
    if (knownTags.length > 0) {
      console.log(`Tags already used for this problem: ${knownTags.map((t) => color('1', `[${t}]`)).join(' ')}`);
    }
    console.log(dim(`This script will not edit the existing block(s); add the tag there yourself.`));
    if (!tag) tag = (await ask('Tag for this approach (blank for none)', '')) || undefined;
  }
  if (tag && !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(tag)) {
    fail(`tag "${tag}" must be lowercase letters, digits and single dashes, e.g. two-pointers.`);
  }

  // 6. Which section?
  const raw = readFileSync(abs, 'utf8');
  const eol = raw.includes('\r\n') ? '\r\n' : '\n';
  const lines = raw.split(eol);
  const banners = findBanners(lines);

  let at: number;
  let indent: number;
  if (banners.length === 0) {
    console.log(yellow(`\n${target.file} has no section banners; appending at the end of the file.`));
    at = lines.length;
    while (at > 0 && lines[at - 1].trim() === '') at--;
    indent = 0;
  } else {
    // Every banner bounds a section, but the trailing test/driver sections are
    // not somewhere a solution can usefully live, so they are not offered.
    const offerable = banners
      .map((b, i) => ({ b, i }))
      .filter(({ b }) => !TAIL_BANNER.test(b.name));
    if (offerable.length === 0) fail(`${target.file} has no section that can hold a solution.`);

    let chosen: number;
    if (flags.section) {
      const wanted = flags.section.trim().toLowerCase();
      const hit = offerable.find(({ b }) => b.name.toLowerCase() === wanted);
      if (!hit) {
        fail(
          `no section "${flags.section}" in ${target.file}.\n` +
            `        Sections: ${offerable.map(({ b }) => b.name).join(', ')}`,
        );
      }
      chosen = hit.i;
    } else {
      chosen = await askChoice(
        `Which section of ${target.file}?`,
        offerable.map(({ b, i }) => ({ label: `${b.name} ${dim(`(line ${b.index + 1})`)}`, value: i })),
      );
    }
    const boundary = banners[chosen + 1]?.index ?? lines.length;
    ({ at, indent } = insertionPoint(lines, banners[chosen].index, boundary, source));
    console.log(dim(`\nSection: ${banners[chosen].name}`));
  }

  // 7. Preview, then confirm.
  const stub = renderStub({ source, lang: target.lang, number, title, url, difficulty, tag, indent });
  printPreview(target.file, lines, at, stub);

  // Appending past the end of a file that has no final newline necessarily adds
  // one. That is the only case where a pre-existing line's bytes change, so say so.
  if (at >= lines.length && !raw.endsWith(eol)) {
    console.log(yellow(`${target.file} has no trailing newline; one will be added before the stub.\n`));
  }

  if (flags.dryRun) {
    console.log(dim('--dry-run: nothing written.\n'));
    return;
  }

  try {
    const status = execFileSync('git', ['status', '--porcelain', '--', target.file], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    });
    if (status.trim()) {
      console.log(yellow(`Heads up: ${target.file} has uncommitted changes. The insert is still safe (nothing`));
      console.log(yellow(`existing is touched), but your diff will mix this stub with your other edits.`));
    }
  } catch {
    // Not a git checkout, or git unavailable. Not worth failing over.
  }

  if (!isTTY) fail('nothing was written: stdin is not a terminal, so the insert cannot be confirmed.\n        Re-run interactively, or use --dry-run to preview.');

  const confirm = (await ask('Insert this? (y/N)', '')).toLowerCase();
  if (confirm !== 'y' && confirm !== 'yes') {
    console.log(dim('Aborted; nothing written.\n'));
    return;
  }

  lines.splice(at, 0, ...stub);
  writeFileSync(abs, lines.join(eol));
  console.log(green(`\nInserted into ${target.file} at line ${at + 1}.`));
  console.log(dim(`Verify with: npm run verify\n`));
}

try {
  await main();
} catch (err) {
  // Ctrl+C / Ctrl+D at a prompt is a normal way to bail out, not a crash.
  if ((err as { code?: string })?.code === 'ABORT_ERR') {
    console.log(dim('\nAborted; nothing written.\n'));
  } else {
    throw err;
  }
} finally {
  closePrompt();
}
